### ISSUE TITLE
Find Delta MFCCs using Librosa

### ISSUE THREAD

**Issue by cegrief** [cegrief/SickBeetz#2]

**Comment by cegrief** [comment]
It seems like the length of each of the frames for the output of MFCC is 512 samples, is this going to be adequate for our purposes, or do we need more precision? @friendly-flame @nakfoury  
(we can get more precision easily, 512 is just the default)

**Comment by armsnyder** [comment]
Yeah 512 is kind of big. I did a test just now and an onset typically has a length between 400-600 samples for 44.1k audio. It makes sense to have a resolution roughly half of what we're measuring, so 256 maybe?

**Comment by friendly-flame** [comment]
Wait I think I just confused myself.

**Comment by friendly-flame** [comment]
512. Too big. What I meant.

**Comment by friendly-flame** [comment]
I totally typed the number 512 just then and GitHub changed it to a 1. Brilliant.

**Comment by friendly-flame** [comment]
I just realized you can edit comments on GitHub. I'm going to do that and delete these.

**Comment by cegrief** [comment]
I've done more snooping and i was completely wrong
Each frame is of length 2048 samples, with a step of 512 (They overlap). I'd imagine they are still too big in this case. Recommendations?

**Comment by cegrief** [comment]
wait does that make any sense at all? I think I'm just confusing myself

**Comment by armsnyder** [comment]
Probably a little big, but I wouldn't differ from the default by more than a factor of 2.

**Comment by cegrief** [comment]
Okay, so basically i was correct before. 512 is the step between windows, 2048 is the length of the window over which the fft is performed. Modifying the step size increases the number of windows we have, so I cut that down by half. I'm not sure if there is any reason to update the window size though.

**Comment by cegrief** [comment]
I've all but finished the audio segmenter, just doing some testing/fine tuning now. If you run segmenter.py it will plot four segments of the audio file "test1.wav". I'm working on adding command line input to specify the file for ease of testing. In other files you will just need to call segment_audio with a signal and its sample rate. It returns an array of audio segments and an array of times that those segments lie. Closing
