### ISSUE TITLE
record button no work safari

### ISSUE THREAD

**Issue by interactiveaudiolab** [cegrief/SickBeetz#59]
see the result here in this lovely picture
![screen shot 2015-05-20 at 10 41 20 am](https://cloud.githubusercontent.com/assets/1305144/7729969/417858a8-fedd-11e4-8a57-070e2022755c.png)

**Comment by cegrief** [comment]
safari does not have navigator.getusermedia(). This will now display an error message and tell the user to go to chrome or firefox.
